version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://medusa:medusa@postgres:5432/medusa
      REDIS_URL: redis://redis:6379
      PORT: 9000
    env_file:
      - .env
    ports:
      - 9000:9000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: unless-stopped
    networks:
      - medusa

  postgres:
    image: postgres:10.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa
      POSTGRES_DB: medusa
    restart: unless-stopped
    networks:
      - medusa
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - medusa
    volumes:
      - redis:/data

volumes:
  postgres:
    driver: local
  redis:
    driver: local
  node_modules:

networks:
  medusa:
    driver: bridge